services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_DB: chaotic_money
      POSTGRES_USER: atsiklov
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
